#!/bin/sh
set -e

if [ -f "/sbin/ldconfig" ]; then
	ldconfig
fi

set +e
# remove copies from the old /etc location
rm -f /etc/systemd/system/mono_depth_rescaler.service
rm -f /etc/systemd/system/voxl-camera-server.service.d/wants-depth.conf
rmdir /etc/systemd/system/voxl-camera-server.service.d 2>/dev/null

systemctl daemon-reload
systemctl reenable mono_depth_rescaler
